$mainMod = SUPER
$terminal = alacritty
$fileManager = thunar
$menu = wofi --show drun
$secMod = SUPER + SHIFT

bind = $mainMod ALT, right, workspace, e+1
bind = $mainMod ALT, left, workspace, e-1
bind = $mainMod, W, killactive,
bind = $mainMod, V, togglefloating,

bind = $mainMod, Space, exec, $menu
bind = $mainMod, P, exec, hyprpicker
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Q, exec, $terminal
bind = $secMod , W, exec, pkill waybar; waybar & disown

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, PRINT, exec, mkdir -p $HOME/Pictures && grim -g "$(slurp)" $HOME/Pictures/$(date +'%Y-%m-%d_%H-%M-%S').png
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit