# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source = ~/.config/hypr/modules/binds.conf
source = ~/.config/hypr/modules/exec.conf
source = ~/.config/hypr/modules/visuals.conf

env = GTK_THEME,Adwaita:dark
env = QT_STYLE_OVERRIDE,Adwaita-Dark
env = XCURSOR_THEME,Breeze
env = XCURSOR_SIZE,24

input {
    accel_profile = flat
    force_no_accel = true
    sensitivity = 0
}

cursor {
    no_hardware_cursors = true
}

xwayland {
    force_zero_scaling = true
}
