general {
    gaps_in = 5
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(0466C8ab)
    col.inactive_border = rgba(33415Cab)
    layout = dwindle
}

decoration {
    rounding = 5

    blur {
        enabled = false      # Turn blur on/off
        size = 3            # Blur radius (size of the blur)
        passes = 1          # More passes = smoother but more GPU intensive
        vibrancy = 0.1696   # How much color to retain in the blurred area
        ignore_opacity = true # Blur remains even if the window is transparent
    }

    shadow {
        enabled = true      # Turn shadows on/off
        range = 4           # Size of the shadow
        render_power = 3    # How fast the shadow fades (1-4)
        color = rgba(1a1a1aee) # Color of the shadow
        # offset = 0, 0     # Optional: [x, y] position offset
    }
}

animations {
    enabled = yes
}